### ISSUE TITLE
Getblocktemplate error

### ISSUE THREAD

**Issue by kr1z1s** [campuscoindev/CC#1] opened 2019-02-14 18:49 UTC
Hello
Version - "version" : 3000200,

> cc-cli getinfo
> {
>     "version" : 3000200,
>     "protocolversion" : 90011,
>     "walletversion" : 61000,
>     "balance" : 0.00000000,
>     "blocks" : 490646,
>     "totalsupply" : 2000000000.00000000,
>     "timeoffset" : 0,
>     "connections" : 37,
>     "proxy" : "",
>     "difficulty" : 6541.78117203,
>     "testnet" : false,
>     "keypoololdest" : 1550121642,
>     "keypoolsize" : 1001,
>     "paytxfee" : 0.00000000,
>     "relayfee" : 0.00010000,
>     "staking status" : "Staking Not Active",
>     "errors" : ""
> }

**ERROR**
cc-cli getblocktemplate 
error: {"code":-7,"message":"Out of memory"}

**Comment by biddyweb** [comment] 2019-02-14 18:56
Will look into that.

**Comment by biddyweb** [comment] 2019-02-14 19:00
Hi @kr1z1s  not able to reproduce this. It seems to work for me. Are you using the official binaries or did you build from source. What OS are your running it on?

**Comment by kr1z1s** [comment] 2019-02-14 19:02
I build from source with optimisation

> uname -a
> Linux 4.4.0-128-generic #154-Ubuntu SMP Fri May 25 14:15:18 UTC 2018 x86_64 x86_64 x86_64 GNU/Linux

**Comment by biddyweb** [comment] 2019-02-14 19:08
I will have to get back to this later. You can try the official binaries they work fine.

**Comment by kr1z1s** [comment] 2019-02-14 19:08
> I will have to get back to this later. You can try the official binaries they work fine.

CFLAGS="-Ofast -march=native -mtune=native -pipe -fPIE" CXXFLAGS="-Ofast -march=native -mtune=native -pipe -fPIE" LDFLAGS="-Ofast -march=native -mtune=native -pipe -fPIE"

**Comment by kr1z1s** [comment] 2019-02-14 19:09
> I will have to get back to this later. You can try the official binaries they work fine.

Not a solution. I want to compile with optimization.

**Comment by biddyweb** [comment] 2019-02-14 19:10
Let me get back to this later tomorrow.

**Comment by kr1z1s** [comment] 2019-02-14 19:28
> Let me get back to this later tomorrow.

Official binary

`ccd: error while loading shared libraries: libzmq.so.5: cannot open shared object file: No such file or directory
`
libzmq-dev and libzmq1 installed

Create softlink, but other error
`ccd: error while loading shared libraries: libdb_cxx-4.8.so: cannot open shared object file: No such file or directory`

I'll wait for a solution. I will not install the old database.

**Comment by biddyweb** [comment] 2019-02-14 19:47
What version of ubuntu are you running?

**Comment by kr1z1s** [comment] 2019-02-14 19:50
> What version of ubuntu are you running?

Ubuntu 16.04.5 LTS (GNU/Linux 4.4.0-128-generic x86_64)

**Comment by Shinoa-Fores** [comment] 2023-04-29 20:50
Closing as issue was likely due to misconfigured env. Reopen if observed again.

**Closed as completed by Shinoa-Fores** 2023-04-29 20:50 UTC
